CREATE OR REPLACE MATERIALIZED VIEW facility_infrastructure AS

SELECT 
FacilityID AS `facility_id`,
FacilityType AS `facility_type`,
FacilityIdentifier AS `facility_identifier`,
FacilityName AS `facility_name`,
FacilitySubType AS `facility_sub_type`,
FacilitySubTypeDesc `facility_sub_type_description`,
ExperimentalConfidential AS `experimental_confidential`,
CAST(FacilityStartDate AS DATE) AS `facility_start_date`,
FacilityLocation AS `facility_location`,
FacilityLegalSubdivision AS `facility_legal_subdivision`,
FacilitySection AS `facility_section`,
FacilityTownship AS `facility_township`,
FacilityRange AS `facility_range`,
FacilityMeridian AS `facility_meridian`,
FacilityLicenceStatus AS `facility_licence_status`,
FacilityOperationalStatus AS `facility_operational_status`,
CAST(FacilityOperationalStatusDate AS DATE) AS `facility_operational_status_date`,
LicenceType AS `licence_type`,
LicenceNumber AS `licence_number`,
EnergyDevelopmentCategoryType AS `energy_development_category_type`,
CAST(LicenceIssueDate AS DATE) AS `licence_issue_date`,
LicenseeBAID AS `licensee_ba_id`,
LicenseeName AS `licensee_name`,
OperatorBAID AS `operator_ba_id`,
OperatorName AS `operator_name`,
CAST(OperatorStartDate AS DATE) AS `operator_start_date`,
TerminalPipelineLink AS `terminal_pipeline_link`,
TPFacilityProvinceState AS `tp_facility_province_state`,
TPFacilityType AS `tp_facility_type`,
TPFacilityIdentifier AS `tp_facility_identifier`,
MeterStationPipelineLink AS `meter_station_pipeline_link`,
MPFacilityProvinceState AS `mp_facility_province_state`,
MPFacilityType AS `mp_facility_type`,
MPFacilityIdentifier AS `mp_facility_identifier`,
EnergyDevelopmentCategoryID AS `energy_development_category_id`,
OrphanWellFlg AS `orphan_well_flag`,
FacilityProvinceState AS `facility_province`
FROM ${source_catalog}.petrinex.facility_infrastructure_ab

UNION

SELECT 
FacilityID AS `facility_id`,
FacilityType AS `facility_type`,
FacilityIdentifier AS `facility_identifier`,
FacilityName AS `facility_name`,
FacilitySubType AS `facility_sub_type`,
FacilitySubTypeDesc `facility_sub_type_description`,
ExperimentalConfidential AS `experimental_confidential`,
CAST(FacilityStartDate AS DATE) AS `facility_start_date`,
FacilityLocation AS `facility_location`,
FacilityLegalSubdivision AS `facility_legal_subdivision`,
FacilitySection AS `facility_section`,
FacilityTownship AS `facility_township`,
FacilityRange AS `facility_range`,
FacilityMeridian AS `facility_meridian`,
FacilityLicenceStatus AS `facility_licence_status`,
FacilityOperationalStatus AS `facility_operational_status`,
CAST(FacilityOperationalStatusDate AS DATE) AS `facility_operational_status_date`,
LicenceType AS `licence_type`,
LicenceNumber AS `licence_number`,
EnergyDevelopmentCategoryType AS `energy_development_category_type`,
CAST(LicenceIssueDate AS DATE) AS `licence_issue_date`,
LicenseeBAID AS `licensee_ba_id`,
LicenseeName AS `licensee_name`,
OperatorBAID AS `operator_ba_id`,
OperatorName AS `operator_name`,
CAST(OperatorStartDate AS DATE) AS `operator_start_date`,
TerminalPipelineLink AS `terminal_pipeline_link`,
TPFacilityProvinceState AS `tp_facility_province_state`,
TPFacilityType AS `tp_facility_type`,
TPFacilityIdentifier AS `tp_facility_identifier`,
MeterStationPipelineLink AS `meter_station_pipeline_link`,
MPFacilityProvinceState AS `mp_facility_province_state`,
MPFacilityType AS `mp_facility_type`,
MPFacilityIdentifier AS `mp_facility_identifier`,
EnergyDevelopmentCategoryID AS `energy_development_category_id`,
OrphanWellFlg AS `orphan_well_flag`,
FacilityProvinceState AS `facility_province`
FROM ${source_catalog}.petrinex.facility_infrastructure_sk;