CREATE OR REPLACE MATERIALIZED VIEW well_infrastructure AS

SELECT 
WellID AS `well_id`,
WellType AS `well_type`,
WellIdentifier AS `well_identifier`,
WellLocationException AS `well_location_exception`,
WellLegalSubdivision AS `well_legal_subdivision`,
WellSection AS `well_section`,
WellTownship AS `well_township`,
WellRange AS `well_range`,
WellMeridian AS `well_meridian`,
WellEventSequence AS `well_vent_sequence`,
WellName AS `well_name`,
ConfidentialType AS `confidential_type`,
ExperimentalConfidentialIndicator AS `experimental_confidential_indicator`,
CAST(ExperimentalConfidentialEffectiveDate AS DATE) AS `experimental_confidential_effective_date`,
CAST(ExperimentalConfidentialTerminationDate AS DATE) AS `experimental_confidential_termination_date`,
LicenceType AS `licence_type`,
LicenceNumber AS `licence_number`,
LinkedFacilityID AS `linked_facility_id`,
LinkedFacilityProvinceState AS `linked_facility_province_state`,
LinkedFacilityType AS `linked_facility_type`,
LinkedFacilityIdentifier AS `linked_facility_identifier`,
LinkedFacilityName AS `linked_facility_name`,
LinkedFacilitySubType AS `linked_facility_sub_type`,
LinkedFacilitySubTypeDesc AS `linked_facility_sub_type_description`,
CAST(LinkedStartDate AS DATE) AS `linked_start_date`,
LinkedFacilityOperatorBAID AS `linked_facility_operator_ba_id`,
LinkedFacilityOperatorLegalName AS `linked_facility_operator_legal_name`,
Field AS `field`,
FieldName AS `field_name`,
Area AS `area`,
AreaName AS `area_name`,
PoolDeposit AS `pool_deposit`,
PoolDepositName AS `pool_deposit_name`,
PoolDepositDensity AS `pool_deposit_density`,
WellStatusFluid AS `well_status_fluid`,
WellStatusMode AS `well_status_mode`,
WellStatusType AS `well_status_type`,
WellStatusStructure AS `well_status_structure`,
WellStatusFluidCode AS `well_status_fluid_code`,
WellStatusModeCode AS `well_status_mode_code`,
WellStatusTypeCode AS `well_status_type_code`,
WellStatusStructureCode AS `well_status_structure_code`,
CAST(WellStatusDate AS DATE) AS `well_status_date`,
CAST(SpudDate AS DATE) AS `spud_date`,
HorizontalDrill AS `horizontal_drill`,
CAST(FinishedDrillDate AS DATE) AS `finished_drill_date`,
FinalTotalDepth AS `final_total_depth`,
MaxTrueVerticalDepth AS `max_true_vertical_depth`,
VolumetricGasWellLiquidType AS `volumetric_gas_well_liquid_type`,
CAST(VolumetricGasWellLiquidEffectiveDate AS DATE) AS `volumetric_gas_well_liquid_effective_date`,
LicenseeID AS `licensee_id`,
LicenseeName AS `licensee_name`,
ComminglingProcessApprovalNumber AS `commingling_process_approval_number`,
ComminglingProcess AS `commingling_process`,
CAST(ComminglingEffDate AS DATE) AS `commingling_eff_date`,
CommingledReportingWellID AS `commingled_reporting_well_id`,
CommingledReportingWellProvinceState AS `commingled_reporting_well_province_state`,
CommingledReportingWellType AS `commingled_reporting_well_type`,
CommingledReportingWellIdentifier AS `commingled_reporting_well_identifier`,
CommingledLinkedFacilityID AS `commingled_linked_facility_id`,
CommingledLinkedFacilityProvinceState AS `commingled_linked_facility_province_state`,
CommingledLinkedFacilityType AS `commingled_linked_facility_type`,
CommingledLinkedFacilityIdentifier AS `commingled_linked_facility_identifier`,
AllowableType AS `allowable_type`,
BlockNumber AS `block_number`,
RecoveryMechanismType AS `recovery_mechanism_type`,
CAST(LicenceIssueDate AS DATE) AS `licence_issue_date`,
CAST(LicenceStatusDate AS DATE) AS `licence_status_date`,
LicenceStatus AS `licence_status`,
PreviousWellID AS `previous_well_id`,
OrphanWellFlg AS `orphan_well_flag`,
WellProvinceState AS `well_province`
FROM ${source_catalog}.petrinex.well_infrastructure_ab

UNION

SELECT 
WellID AS `well_id`,
WellType AS `well_type`,
WellIdentifier AS `well_identifier`,
WellLocationException AS `well_location_exception`,
WellLegalSubdivision AS `well_legal_subdivision`,
WellSection AS `well_section`,
WellTownship AS `well_township`,
WellRange AS `well_range`,
WellMeridian AS `well_meridian`,
WellEventSequence AS `well_vent_sequence`,
WellName AS `well_name`,
ConfidentialType AS `confidential_type`,
ExperimentalConfidentialIndicator AS `experimental_confidential_indicator`,
CAST(ExperimentalConfidentialEffectiveDate AS DATE) AS `experimental_confidential_effective_date`,
CAST(ExperimentalConfidentialTerminationDate AS DATE) AS `experimental_confidential_termination_date`,
LicenceType AS `licence_type`,
LicenceNumber AS `licence_number`,
LinkedFacilityID AS `linked_facility_id`,
LinkedFacilityProvinceState AS `linked_facility_province_state`,
LinkedFacilityType AS `linked_facility_type`,
LinkedFacilityIdentifier AS `linked_facility_identifier`,
LinkedFacilityName AS `linked_facility_name`,
LinkedFacilitySubType AS `linked_facility_sub_type`,
LinkedFacilitySubTypeDesc AS `linked_facility_sub_type_description`,
CAST(LinkedStartDate AS DATE) AS `linked_start_date`,
LinkedFacilityOperatorBAID AS `linked_facility_operator_ba_id`,
LinkedFacilityOperatorLegalName AS `linked_facility_operator_legal_name`,
Field AS `field`,
FieldName AS `field_name`,
Area AS `area`,
AreaName AS `area_name`,
PoolDeposit AS `pool_deposit`,
PoolDepositName AS `pool_deposit_name`,
PoolDepositDensity AS `pool_deposit_density`,
WellStatusFluid AS `well_status_fluid`,
WellStatusMode AS `well_status_mode`,
WellStatusType AS `well_status_type`,
WellStatusStructure AS `well_status_structure`,
WellStatusFluidCode AS `well_status_fluid_code`,
WellStatusModeCode AS `well_status_mode_code`,
WellStatusTypeCode AS `well_status_type_code`,
WellStatusStructureCode AS `well_status_structure_code`,
CAST(WellStatusDate AS DATE) AS `well_status_date`,
CAST(SpudDate AS DATE) AS `spud_date`,
HorizontalDrill AS `horizontal_drill`,
CAST(FinishedDrillDate AS DATE) AS `finished_drill_date`,
FinalTotalDepth AS `final_total_depth`,
MaxTrueVerticalDepth AS `max_true_vertical_depth`,
VolumetricGasWellLiquidType AS `volumetric_gas_well_liquid_type`,
CAST(VolumetricGasWellLiquidEffectiveDate AS DATE) AS `volumetric_gas_well_liquid_effective_date`,
LicenseeID AS `licensee_id`,
LicenseeName AS `licensee_name`,
ComminglingProcessApprovalNumber AS `commingling_process_approval_number`,
ComminglingProcess AS `commingling_process`,
CAST(ComminglingEffDate AS DATE) AS `commingling_eff_date`,
CommingledReportingWellID AS `commingled_reporting_well_id`,
CommingledReportingWellProvinceState AS `commingled_reporting_well_province_state`,
CommingledReportingWellType AS `commingled_reporting_well_type`,
CommingledReportingWellIdentifier AS `commingled_reporting_well_identifier`,
CommingledLinkedFacilityID AS `commingled_linked_facility_id`,
CommingledLinkedFacilityProvinceState AS `commingled_linked_facility_province_state`,
CommingledLinkedFacilityType AS `commingled_linked_facility_type`,
CommingledLinkedFacilityIdentifier AS `commingled_linked_facility_identifier`,
AllowableType AS `allowable_type`,
BlockNumber AS `block_number`,
RecoveryMechanismType AS `recovery_mechanism_type`,
CAST(LicenceIssueDate AS DATE) AS `licence_issue_date`,
CAST(LicenceStatusDate AS DATE) AS `licence_status_date`,
LicenceStatus AS `licence_status`,
PreviousWellID AS `previous_well_id`,
OrphanWellFlg AS `orphan_well_flag`,
WellProvinceState AS `well_province`
FROM ${source_catalog}.petrinex.well_infrastructure_sk