CREATE OR REPLACE MATERIALIZED VIEW well_to_facility_link AS

SELECT 
WellID AS `well_id`,
WellType AS `well_type`,
WellIdentifier AS `well_identifier`,
WellLocationException AS `well_location_exception`,
WellLegalSubdivision AS `well_legal_subdivision`,
WellSection AS `well_section`,
WellTownship AS `well_township`,
WellRange AS `well_range`,
WellMeridian AS `well_meridian`,
WellEventSequence AS `well_event_sequence`,
WellName AS `well_name`,
WellStatusFluid AS `well_status_fluid`,
WellStatusMode AS `well_status_mode`,
WellStatusType AS `well_status_type`,
WellStatusStructure AS `well_status_structure`,
WellStatusFluidCode AS `well_status_fluid_code`,
WellStatusModeCode AS `well_status_mode_code`,
WellStatusTypeCode AS `well_status_type_code`,
WellStatusStructureCode AS `well_status_structure_code`,
CAST(WellStatusStartDate AS DATE) AS `well_status_start_date`,
LinkedFacilityID AS `linked_facility_id`,
LinkedFacilityProvinceState AS `linked_facility_province_state`,
LinkedFacilityType AS `linked_facility_type`,
LinkedFacilityIdentifier AS `linked_facility_identifier`,
LinkedFacilityName AS `linked_facility_name`,
LinkedFacilitySubType AS `linked_facility_sub_type`,
LinkedFacilitySubTypeDesc AS `linked_facility_sub_type_description`,
CAST(LinkedStartDate AS DATE) AS `linked_start_date`,
LinkedFacilityOperatorBAID AS `linked_facility_operator_ba_id`,
LinkedFacilityOperatorName AS `linked_facility_operator_name`,
WellProvinceState AS `well_province`
FROM ${source_catalog}.petrinex.well_to_facility_link_ab

UNION

SELECT 
WellID AS `well_id`,
WellType AS `well_type`,
WellIdentifier AS `well_identifier`,
WellLocationException AS `well_location_exception`,
WellLegalSubdivision AS `well_legal_subdivision`,
WellSection AS `well_section`,
WellTownship AS `well_township`,
WellRange AS `well_range`,
WellMeridian AS `well_meridian`,
WellEventSequence AS `well_event_sequence`,
WellName AS `well_name`,
WellStatusFluid AS `well_status_fluid`,
WellStatusMode AS `well_status_mode`,
WellStatusType AS `well_status_type`,
WellStatusStructure AS `well_status_structure`,
WellStatusFluidCode AS `well_status_fluid_code`,
WellStatusModeCode AS `well_status_mode_code`,
WellStatusTypeCode AS `well_status_type_code`,
WellStatusStructureCode AS `well_status_structure_code`,
CAST(WellStatusStartDate AS DATE) AS `well_status_start_date`,
LinkedFacilityID AS `linked_facility_id`,
LinkedFacilityProvinceState AS `linked_facility_province_state`,
LinkedFacilityType AS `linked_facility_type`,
LinkedFacilityIdentifier AS `linked_facility_identifier`,
LinkedFacilityName AS `linked_facility_name`,
LinkedFacilitySubType AS `linked_facility_sub_type`,
LinkedFacilitySubTypeDesc AS `linked_facility_sub_type_description`,
CAST(LinkedStartDate AS DATE) AS `linked_start_date`,
LinkedFacilityOperatorBAID AS `linked_facility_operator_ba_id`,
LinkedFacilityOperatorName AS `linked_facility_operator_name`,
WellProvinceState AS `well_province`
FROM ${source_catalog}.petrinex.well_to_facility_link_sk